import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
const require = createRequire(new URL('../frontend/package.json', import.meta.url))
const { build } = require('esbuild')
const built = await build({entryPoints:[fileURLToPath(new URL('../frontend/src/workbench/replay.ts', import.meta.url))], bundle:true,write:false,platform:'node',format:'cjs'})
const module = {exports:{}}
new Function('require','module','exports',built.outputFiles[0].text)(require,module,module.exports)
const { ReplayTimeline } = module.exports
const frame = (index,time) => ({index,offset_ms:time,message:{service_id:0x1234,method_id:0x8001,signal_values:{counter:18446744073709551615n}}})
const clock = new ReplayTimeline()
clock.load({frames:[frame(0,0),frame(1,100),frame(2,200)], next_offset:3,complete:false,wire_replay:false})
assert.equal(clock.playing,false)
assert.equal(clock.step()[0].index,0)
assert.equal(clock.advance(500).length,0)
clock.play(1000)
assert.equal(clock.advance(1050).length,0)
assert.equal(clock.advance(1100)[0].index,1)
clock.pause()
assert.equal(clock.advance(2000).length,0)
assert.equal(clock.position,100)
clock.play(2000)
clock.setRate(2,2000)
assert.equal(clock.advance(2050)[0].index,2)
assert.equal(clock.buffered,0)
clock.advance(3050)
assert.equal(clock.position,200,'等待下一页不能推进时间')
clock.load({frames:[frame(3,300)],next_offset:4,complete:true,wire_replay:false})
clock.play(4000)
assert.equal(clock.advance(4050)[0].message.signal_values.counter,18446744073709551615n)
assert.equal(clock.ended,true)
assert.equal(clock.playing,false)
clock.reset(500)
assert.equal(clock.position,500)
assert.equal(clock.nextOffset,0)
assert.throws(()=>clock.setRate(0,5000))
assert.throws(()=>clock.reset(NaN))
assert.throws(()=>clock.load({frames:[frame(1,50),frame(0,20)],next_offset:2,complete:true,wire_replay:false}))
const bounded = new ReplayTimeline()
bounded.load({frames:Array.from({length:1000},(_,i)=>frame(i,0)),next_offset:1000,complete:true,wire_replay:false})
bounded.play(0)
assert.equal(bounded.advance(0).length,256)
assert.equal(bounded.buffered,744)
console.info('离线回放时间轴验收通过：暂停、单步、倍率、分页等待、跳转、顺序校验和有界释放；不会执行网络发送。')
